

on:
  release:
    types: [created]


env:
  DOWNLOAD_RELEASE_TEMP_PATH: ${{ github.workspace }}/modloader-temp
  #  MODLOADER_HTML_FILENAME: "Degrees of Lewdity VERSION.html.mod-polyfill.html"

  MODLOADER_HTML_NORMAL_FILENAME: "Degrees of Lewdity VERSION.html.mod.html"
  MODLOADER_HTML_POLYFILL_FILENAME: "Degrees of Lewdity VERSION.html.mod-polyfill.html"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Make Directories
        run: |
          mkdir -p "${{ env.DOWNLOAD_RELEASE_TEMP_PATH }}/mods"
      
      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"
      
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      
      - name: Setup Android SDKr
        uses: android-actions/setup-android@v3
        with: 
          cmdline-tools-version: 11.0
      
      - run: sdkmanager "build-tools;32.0.0" "platforms;android-32"

      - id: getModLoaderRelease
        name: Download ModLoader Build
        uses: robinraju/release-download@latest
        with:
          repository: "Lyoko-Jeremie/DoLModLoaderBuild"
          latest: true
          fileName: "DoL-ModLoader-*.zip"
      
      - name: Extract ModLoader Build
        run: |
          unzip -q ${{ fromJson(steps.getModLoaderRelease.outputs.downloaded_files)[0] }} -d ${{ env.DOWNLOAD_RELEASE_TEMP_PATH }}
